@startuml system

rectangle edge {
    component LocalCoAPServer
    component SensorNoInternet
    component SensorInternet
    interface CoAP1
    interface CoAP2
} 

rectangle gateway {
    rectangle STMBroker {
        component "ID : IP"
        component "ID : List[SUB]"
    }
    component UDPChannelStream 
    queue     EffectStream
    queue     ChunkStream
    queue     CoAPPacketStream as CPS1
    queue     JSONStreams as JS1

    queue     JSONStreams as JS2
    queue     CoAPPacketStream as CPS2
    queue     CoAPPacketQueue

    component WebSocketStream
} 


rectangle "Common Operational Picture (Akka)" as COP
rectangle "Operational Sub-Picture (Actors)" as OSP1
rectangle "Operational Sub-Picture (Actors)" as OSP2

actor user

CoAP1 .. UDPChannelStream : unique sensor id
CoAP2 .. UDPChannelStream : unique sensor id

LocalCoAPServer .. SensorNoInternet
SensorInternet  .. CoAP1
LocalCoAPServer .. CoAP2

UDPChannelStream .down.>   EffectStream : repeat receive forever
EffectStream     .right.>  ChunkStream : received buffer to chunk
ChunkStream      .right.>  CPS1 : chunk to packet
CPS1             .right.>  JS1
JS1              .right.>  WebSocketStream

WebSocketStream  .up.>     JS2
JS2              .left.>   CPS2
CPS2             .left.>   CoAPPacketQueue
CoAPPacketQueue  .left.>   UDPChannelStream

STMBroker        <.left.> WebSocketStream : id:sub
UDPChannelStream .right.>   STMBroker : id:ip

OSP1 <.> WebSocketStream : enter sub/provide sub data
OSP2 <.> WebSocketStream : send sensor commands

user <..> COP
COP  <..> WebSocketStream : admin/logging
COP  <..> OSP1
COP  <..> OSP2

@enduml